// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1vqFpFwXXLMB8e3S-pLj04TJnJpkgNcY',
    appId: '1:527768456077:web:a67e403334f687f6880bc4',
    messagingSenderId: '527768456077',
    projectId: 'quickly-a9335',
    authDomain: 'quickly-a9335.firebaseapp.com',
    storageBucket: 'quickly-a9335.appspot.com',
    measurementId: 'G-5GD1N4293S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGe8G3Zrm2TofNPRkuvcTaZfGItatmQOs',
    appId: '1:527768456077:android:e2dd2296bc887314880bc4',
    messagingSenderId: '527768456077',
    projectId: 'quickly-a9335',
    storageBucket: 'quickly-a9335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6pSbN2uXwP--YloqJflHhyhque2U2p0E',
    appId: '1:527768456077:ios:1bc197ae9f535fc8880bc4',
    messagingSenderId: '527768456077',
    projectId: 'quickly-a9335',
    storageBucket: 'quickly-a9335.appspot.com',
    iosBundleId: 'com.example.seasons',
  );
}
