import 'translation_key_manager.dart';

Map<String, String> ar = {
  // public
  TranslationKeyManager.main: 'الرئيسية',
  TranslationKeyManager.bookNow: 'احجز الان',
  TranslationKeyManager.usd: 'دولار',
  TranslationKeyManager.firstName: 'الاسم الاول',
  TranslationKeyManager.lastName: 'الاسم الاخير',
  TranslationKeyManager.phoneNumber: 'رقم الهاتف',
  TranslationKeyManager.email: 'البريد الالكتروني',
  TranslationKeyManager.fromDate: 'من تاريخ',
  TranslationKeyManager.toDate: 'حتي تاريخ',
  TranslationKeyManager.daysCount: 'عدد الايام',
  TranslationKeyManager.total: 'الاجمالي',
  TranslationKeyManager.tax: 'الضريبة',
  TranslationKeyManager.net: 'الصافي',

  // login
  TranslationKeyManager.login: 'تسجيل الدخول',
  TranslationKeyManager.userName: 'اسم المستخدم',
  TranslationKeyManager.password: 'الرقم السري',
  TranslationKeyManager.loginTitle: "سجل في حساب الوكيل الخاص بك",
  TranslationKeyManager.loginHint:
      "حتي تتمكن من اداره حسابك في منصة مواسم السياحة",

  // OnBoarding
  TranslationKeyManager.onBoardBookInquiry: 'الاستلام عن الحجوزات بكود الحجز',
  TranslationKeyManager.onBoardBookInquiryBtn: 'استعلام عن الحجز',

  TranslationKeyManager.booksInquiry: 'الاستعلام عن الحجوزات',
  TranslationKeyManager.bookSearchCodeBtn: 'ابحث بكود تأكيد الحجز',
  TranslationKeyManager.ex: 'مثل',
  TranslationKeyManager.bookInquiryBtn: 'استعلم',

  TranslationKeyManager.onBoardBookFlightTitle: 'حجز الطيران',
  TranslationKeyManager.onBoardBookFlight: "يمكنك الان حجز رحلتك بضغطة زر",
  TranslationKeyManager.onBoardBookFlightBtn: 'حجز الطيران',

  TranslationKeyManager.onBoardBookTourismTitle: 'حجز البرامج السياحية',
  TranslationKeyManager.onBoardBookTourism: "يمكنك حجز برنامج سياحي بسهولة",
  TranslationKeyManager.onBoardBookTourismBtn: 'البرامج السياحية',

  TranslationKeyManager.onBoardBookHotelsTitle: 'حجز الفنادق',
  TranslationKeyManager.onBoardBookHotels:
      "اختر فندق لاقامتك من بين مجموعة مميزة من الفنادق",
  TranslationKeyManager.onBoardBookHotelsBtn: 'احجز الان',

  TranslationKeyManager.onBoardBookCarsTitle: 'حجز السيارات',
  TranslationKeyManager.onBoardBookCars: "اختر سيارتك الان سيدان، فان او باص",
  TranslationKeyManager.onBoardBookCarsBtn: 'احجز الان',

  TranslationKeyManager.onBoardShowMore: 'يمكنك استعراض المزيد',
  TranslationKeyManager.onBoardSkipBtn: 'تخطي',

  // bottom navigation
  TranslationKeyManager.bottomNavMore: 'المزيد',
  TranslationKeyManager.bottomNavTourism: 'سياحة',
  TranslationKeyManager.bottomNavHotels: 'فنادق',
  TranslationKeyManager.bottomNavFlight: 'طيران',
  TranslationKeyManager.bottomNavHome: 'الرئيسية',
  TranslationKeyManager.allNeed: 'كل ما تحتاجه لرحلتك',
  TranslationKeyManager.recentSearch: 'البحث الاخير',
  TranslationKeyManager.canHelp: 'يمكننا المساعدة؟',

  //hotels

  TranslationKeyManager.hotelBook: 'حجز الفندق',
  TranslationKeyManager.hotelDetails: 'تفاصيل الفندق',
  TranslationKeyManager.hotelData: 'بيانات الفندق',
  TranslationKeyManager.hotelName: 'اسم الفندق',
  TranslationKeyManager.hotelRate: 'تقييم الفندق',
  TranslationKeyManager.stars: 'نجوم',
  TranslationKeyManager.hotelType: 'نوع الفندق',
  TranslationKeyManager.roomChoose: 'اختر الغرفة',
  TranslationKeyManager.singleRoom: 'غرفة فردية',
  TranslationKeyManager.doubleRoom: 'غرفة مزدوجة',
  TranslationKeyManager.tripleRoom: 'غرفة ثلاثية',
  TranslationKeyManager.childBook: 'حجز الاطفال',
  TranslationKeyManager.noChild: 'لا يوجد',
  TranslationKeyManager.childWithBed: 'حجز طفل بسرير',
  TranslationKeyManager.childWithoutBed: 'حجز طفل بدون سرير',
  TranslationKeyManager.roomPricePerDay: 'سعر الغرفة في الليلة',
  TranslationKeyManager.showAll: 'عرض الكل',

  // car
  TranslationKeyManager.cars: 'السيارات',
  TranslationKeyManager.carBook: 'حجز السيارة',
  TranslationKeyManager.carType: 'نوع السيارة',
  TranslationKeyManager.withDriverQues: 'هل تحتاج سائق ؟',
  TranslationKeyManager.withDriver: 'وجود سائق',
  TranslationKeyManager.withoutDriver: 'عدم وجود سائق',
  TranslationKeyManager.pricePerDay: 'السعر في اليوم ؟',
  TranslationKeyManager.notes: 'ملاحظات',
  TranslationKeyManager.notesHint:
      'من فضلك اكتب ملاحظاتك ثم اختر المطار والوقت المحلي للوصول',
  TranslationKeyManager.next: 'التالي',
  TranslationKeyManager.defValidation: 'لا يجب ان يكون فارغ',

  // settings
  TranslationKeyManager.settings: 'الاعدادات',
  TranslationKeyManager.versionNumber: 'رقم النسخة',
  TranslationKeyManager.language: 'اللغة',
  TranslationKeyManager.seasonsTour: 'مواسم السياحة',
  TranslationKeyManager.aboutUs: 'عن مواسم السياحة',
  TranslationKeyManager.privacyPolicy: 'سياسة الخصوصية',
  TranslationKeyManager.contactUs: 'تواصل معنا',
  TranslationKeyManager.contactUsBio:
      'يسعدنا دائما في مواسم السياحة تواصلكم معنا عبر احد الوسائل المتوفرة كما يسعدنا مساعدتكم دائما',
  TranslationKeyManager.contactsMethods: 'وسائل التواصل',
  TranslationKeyManager.via: 'عبر',
  TranslationKeyManager.whatsApp: 'واتس اب',
  TranslationKeyManager.facebook: 'فيسبوك',
  TranslationKeyManager.twitter: "توتير",
  TranslationKeyManager.telegram: "تليجرام",
  TranslationKeyManager.youtube: "يوتيوب",
  TranslationKeyManager.instagram: "انستجرام",
  TranslationKeyManager.snapchat: "اسناب شات",
  TranslationKeyManager.tiktok: "تك توك",
  TranslationKeyManager.messenger: "ماسنجر",
  TranslationKeyManager.googlePlayLink: "لينك المتجر",
  TranslationKeyManager.appStoreLink: "لينك ابل استور",
  TranslationKeyManager.mobileNumber: "موبيل",
  TranslationKeyManager.followUs: 'تابعنا من خلال',

  // flight
  TranslationKeyManager.flightTitle: 'حجز الطيران',
  TranslationKeyManager.oneWay: 'ذهاب فقط',
  TranslationKeyManager.goingAndComingBack: 'ذهاب وعودة',
  TranslationKeyManager.travelFrom: 'السفر من',
  TranslationKeyManager.arriveTo: 'الوصول الي',
  TranslationKeyManager.choose: 'اختر',
  TranslationKeyManager.close: 'اغلق',
  TranslationKeyManager.departureDate: 'تاريخ المغادرة',
  TranslationKeyManager.whereFrom: 'من أين؟',
  TranslationKeyManager.numberOfAdults: 'عدد البالغين',
  TranslationKeyManager.yearsOld12: '+12 سنه',
  TranslationKeyManager.numberOfChildren2: 'عدد الاطفال 2',
  TranslationKeyManager.years11: '-11 سنه',
  TranslationKeyManager.numberOfInfantsFrom: 'عدد الرضع من',
  TranslationKeyManager.yearsOld02: '2-0 سنه',
  TranslationKeyManager.search: 'ابحث',
  TranslationKeyManager.allAirports: 'جميع المطارات',
  TranslationKeyManager.results: 'نتائج',
  TranslationKeyManager.Continue: 'الاستمرار',
  TranslationKeyManager.whereTo: 'الي أين؟',
  TranslationKeyManager.passengers: 'ركاب',
  TranslationKeyManager.haveAccount: 'هل لديك حساب؟',
  TranslationKeyManager.loginFaster: 'تسجيل الدخول بشكل اسرع',
  TranslationKeyManager.contactDetails: 'بيانات المتصل',
  TranslationKeyManager.nationality: 'الجنسية',
  TranslationKeyManager.passportNum: 'رقم جواز السفر',
  TranslationKeyManager.availableFlights: 'الرحلات المتاحة',
  TranslationKeyManager.allTaxes: 'شامل جميع الضرائب والرسوم',
  TranslationKeyManager.checkedBaggage: 'يشمل سعر الامتعة المسجلة',
  TranslationKeyManager.roundTrip: 'جولة',
  TranslationKeyManager.changeDate: 'حاول تغيير التواريخ او الواجهة',
  TranslationKeyManager.noResult:
      'لم نعثر علي اي نتائج تطابق معايير البحث الخاصة بك',
  TranslationKeyManager.sorry: 'آسفون...',
  TranslationKeyManager.searchFlight: 'البحث عن الرحلات الجوية',
  TranslationKeyManager.when: 'متي ؟',
  TranslationKeyManager.onlyFlight: 'الرحلات المباشرة فقط',
  TranslationKeyManager.dateRange: 'الرجاء اختيار نطاق التاريخ الخاص بك',

  // tourism
  TranslationKeyManager.tourismTitle: 'البرامج السياحية',
  TranslationKeyManager.includeFlight: "يشمل الطيران",
  TranslationKeyManager.notIncludeFlight: "لا يشمل الطيران",
  TranslationKeyManager.city: 'المدينة',
  TranslationKeyManager.cities: 'المدن',
  TranslationKeyManager.chooseCountry: 'الرجاء اختيار بلدك أولا',
  TranslationKeyManager.noCities: 'آسف لاتوجد مدن',
  TranslationKeyManager.country: 'الدولة',
  TranslationKeyManager.countries: 'الدول',
  TranslationKeyManager.serverError: 'آسف، خطأ في الخادم يرجي المحاولة مرة آخري في وقت لاحق',
  TranslationKeyManager.chooseRoom: "اختيار غرفة",
  TranslationKeyManager.roomType: "نوع الغرفة",
  TranslationKeyManager.kidsReservation: "حجز الاطفال",
  TranslationKeyManager.kidsCount: "عدد الاطفال",
};
